imports:
  - path: instance-template.jinja
resources:
  # Create the auto-mode network
  - name: mynetwork
    type: compute.v1.network
    properties:
      autoCreateSubnetworks: true
  - name: mynetwork-allow-http-ssh-rdp-icmp
    type: compute.v1.firewall
    properties:
      network: $(ref.mynetwork.selfLink)
      sourceRanges: ["0.0.0.0/0"]
      allowed:
        - IPProtocol: TCP
          ports: [22, 80, 3389]
        - IPProtocol: ICMP
  - name: mynet-us-vm
    type: instance-template.jinja
    properties:
      zone: us-central1-a
      machineType: n1-standard-1
      network: $(ref.mynetwork.selfLink)
      subnetwork: regions/us-central1/subnetworks/mynetwork
  - name: mynet-eu-vm
    type: instance-template.jinja
    properties:
      zone: europe-west1-d
      machineType: n1-standard-1
      network: $(ref.mynetwork.selfLink)
      subnetwork: regions/europe-west1/subnetworks/mynetwork
